import { assetCategories, projectCategories } from "./company";
import {financeCatalog} from './finance-catalog';
export type Field = {
  key: string;
  label: string;
  type?: "text" | "textarea" | "number" | "date" | "datetime-local" | "email" | "money" | "decimal";
  required?: boolean;
  options?: string[];
  ref?: string;
  min?: number;
  max?: number;
};
export type Entity = {
  label: string;
  singular: string;
  prefix: string;
  description: string;
  fields: Field[];
  statuses: string[];
  columns: string[];
  computed?: string[];
  create?: boolean;
  edit?: boolean;
};
const f = (key: string, label: string, type: Field["type"] = "text", required = false): Field => ({
  key,
  label,
  type,
  required,
});
const r = (key: string, label: string, ref: string, required = false): Field => ({
  key,
  label,
  ref,
  required,
});
const o = (key: string, label: string, options: string[], required = false): Field => ({
  key,
  label,
  options,
  required,
});
const customer = r("customer_id", "Customer", "customers", true);
const site = r("site_id", "Site", "sites", true);
const asset = r("equipment_id", "Asset", "equipment", true);
const engineer = r("engineer_id", "Engineer", "engineers");
const notes = f("notes", "Notes", "textarea");
const title = f("name", "Name / description", "text", true);
const priority = o("priority", "Priority", ["Low", "Normal", "High", "Emergency"], true);
const num = (key: string, label: string, min = 0, max?: number): Field => ({
  ...f(key, label, "number", true),
  min,
  max,
});
function entity(
  label: string,
  singular: string,
  prefix: string,
  description: string,
  fields: Field[],
  statuses: string[],
  columns: string[],
  extra: Partial<Entity> = {},
): Entity {
  return {
    label,
    singular,
    prefix,
    description,
    fields: [title, ...fields],
    statuses,
    columns,
    create: true,
    edit: true,
    ...extra,
  };
}
export const catalog: Record<string, Entity> = {
  ...financeCatalog,
  customers: entity(
    "Customers",
    "Customer",
    "CUS",
    "Everything related to each customer, their sites, assets and service history in one place.",
    [
      o(
        "type",
        "Customer type",
        [
          "Commercial",
          "Hospitality",
          "Industrial",
          "Office Complex",
          "Retail",
          "Facilities Management",
          "Marine",
          "Government",
          "Residential",
        ],
        true,
      ),
      f("phone", "Phone"),
      f("email", "Email", "email"),
      f("address", "Address", "textarea"),
      notes,
    ],
    ["Active", "Inactive", "Archived"],
    [
      "type",
      "primary_contact",
      "phone",
      "sites_count",
      "active_projects",
      "equipment_count",
      "amc_count",
      "open_complaints",
    ],
    {
      computed: [
        "primary_contact",
        "sites_count",
        "active_projects",
        "equipment_count",
        "amc_count",
        "open_complaints",
      ],
    },
  ),
  contacts: entity(
    "Contacts",
    "Contact",
    "CON",
    "People who keep your customer relationships moving.",
    [
      customer,
      f("role", "Contact role"),
      f("phone", "Phone"),
      f("email", "Email", "email"),
      o("preferred_method", "Preferred contact", ["Phone", "Email", "In Person"]),
      notes,
    ],
    ["Active", "Inactive"],
    ["customer_id", "role", "phone"],
  ),
  sites: entity(
    "Sites",
    "Site",
    "SIT",
    "Every location, its access details and operational context.",
    [
      customer,
      r("contact_id", "Site contact", "contacts"),
      f("address", "Address", "textarea", true),
      f("location", "City / location", "text", true),
      f("access_instructions", "Access instructions", "textarea"),
      notes,
    ],
    ["Active", "Inactive", "Archived"],
    ["customer_id", "location", "equipment_count", "open_complaints", "active_jobs"],
    { computed: ["equipment_count", "open_complaints", "active_jobs"] },
  ),
  enquiries: entity(
    "Enquiries",
    "Enquiry",
    "ENQ",
    "Track requests from the first conversation to a won opportunity.",
    [
      customer,
      site,
      r("contact_id", "Contact", "contacts"),
      f("received_date", "Received date", "date", true),
      o("source", "Source", ["Phone", "Email", "Website", "Referral", "Walk In"]),
      o("category", "Category", [
        "Service",
        "Installation",
        "Maintenance",
        "AMC",
        "Replacement",
        "MEP Services",
        "BMS & Controls",
        "Electrical",
        "Mechanical",
        "Engineering",
        "Facilities Maintenance",
        "Marine Maintenance",
      ]),
      f("description", "Requirement", "textarea", true),
      priority,
      r("assigned_to", "Assigned employee", "profiles"),
      f("followup_date", "Next follow-up", "date"),
      notes,
    ],
    [
      "New",
      "Reviewing",
      "Quotation Required",
      "Quotation Prepared",
      "Waiting Customer",
      "Won",
      "Lost",
      "Closed",
    ],
    ["customer_id", "category", "priority", "followup_date"],
  ),
  enquiry_activities: entity(
    "Enquiry activity",
    "Note",
    "ENA",
    "Notes and follow-ups for this enquiry.",
    [
      r("enquiry_id", "Enquiry", "enquiries", true),
      f("followup_date", "Follow-up date", "date"),
      notes,
    ],
    ["Recorded"],
    ["enquiry_id", "followup_date"],
  ),
  quotations: entity(
    "Quotations",
    "Quotation",
    "QTN",
    "A clear commercial pipeline, from preparation to approval.",
    [
      customer,
      site,
      r("enquiry_id", "Linked enquiry", "enquiries"),
      f("quotation_date", "Quotation date", "date", true),
      f("valid_until", "Valid until", "date", true),
      f("followup_date", "Follow-up date", "date"),
      r("salesperson_id", "Sales person", "profiles"),
      notes,
    ],
    [
      "Draft",
      "Ready",
      "Sent",
      "Follow-Up",
      "Revision Requested",
      "Approved",
      "Rejected",
      "Expired",
    ],
    ["customer_id", "quotation_date", "valid_until", "followup_date"],
  ),
  quotation_items: entity(
    "Line items",
    "Line item",
    "ITM",
    "Itemized pricing in Omani Rial.",
    [
      r("quotation_id", "Quotation", "quotations", true),
      {...num("quantity", "Quantity", 0.001),type:'decimal'},
      f("unit", "Unit", "text", true),
      {...num("unit_price", "Unit price (OMR)"),type:'money'},
      {...num("discount", "Discount (%)", 0, 100),type:'decimal'},
      {...num("tax", "VAT (%)", 0, 100),type:'decimal'},
    ],
    ["Active"],
    ["quantity", "unit", "unit_price", "discount", "tax"],
  ),
  quotation_followups: entity(
    "Follow-ups",
    "Follow-up",
    "FUP",
    "Keep the next customer conversation on schedule.",
    [
      r("quotation_id", "Quotation", "quotations", true),
      f("followup_date", "Follow-up date", "date", true),
      notes,
    ],
    ["Due", "Completed"],
    ["quotation_id", "followup_date"],
  ),
  projects: entity(
    "Projects",
    "Project",
    "PRJ",
    "Engineering, refurbishment, installation and maintenance projects with complete commercial context.",
    [
      customer,
      site,
      r("quotation_id", "Approved quotation", "quotations"),
      o("type", "Project type", projectCategories),
      f("description", "Scope of work", "textarea"),
      f("start_date", "Start date", "date"),
      f("target_date", "Target completion", "date"),
      r("manager_id", "Project manager", "profiles"),
      num("progress", "Progress (%)", 0, 100),
      notes,
    ],
    ["Planning", "Active", "On Hold", "Completed", "Cancelled"],
    ["customer_id", "target_date", "progress"],
  ),
  project_engineers: entity(
    "Project team",
    "Team assignment",
    "PTM",
    "Engineers assigned to this project.",
    [r("project_id", "Project", "projects", true), r("engineer_id", "Engineer", "engineers", true)],
    ["Assigned"],
    ["project_id", "engineer_id"],
  ),
  equipment: entity(
    "Assets",
    "Asset",
    "AST",
    "Mechanical, electrical, HVAC, controls and marine assets with warranty, AMC and complete service history.",
    [
      customer,
      site,
      r("project_id", "Installed under project", "projects"),
      r("amc_id", "AMC contract", "amc_contracts"),
      o("type", "Asset type", assetCategories, true),
      f("brand", "Brand", "text", true),
      f("model", "Model"),
      f("serial_number", "Serial number"),
      f("capacity", "Capacity"),
      f("installation_date", "Installation date", "date"),
      f("commissioning_date", "Commissioning date", "date"),
      f("warranty_start", "Warranty start", "date"),
      f("warranty_end", "Warranty end", "date"),
      o("service_frequency", "Service frequency", ["Monthly", "Quarterly", "Semiannual", "Annual"]),
      f("last_service", "Last service", "date"),
      f("next_service", "Next service", "date"),
      notes,
    ],
    ["Active", "Under Maintenance", "Out of Service", "Retired"],
    ["customer_id", "site_id", "type", "warranty_end", "next_service"],
  ),
  complaints: entity(
    "Service Desk",
    "Service Case",
    "CMP",
    "Warranty, AMC and paid service cases across building services, engineering, facilities and marine maintenance.",
    [
      customer,
      site,
      asset,
      f("reported_by", "Reported by"),
      f("problem", "Reported problem", "textarea", true),
      priority,
      notes,
    ],
    [
      "New",
      "Acknowledged",
      "Assigned",
      "Engineer En Route",
      "In Progress",
      "Waiting Parts",
      "Waiting Customer",
      "Resolved",
      "Closed",
    ],
    ["customer_id", "equipment_id", "priority", "classification", "engineer_id"],
  ),
  engineers: entity(
    "Engineers",
    "Engineer",
    "ENG",
    "Specialists in HVAC, MEP, controls, electrical, mechanical, facilities and marine services.",
    [
      r("profile_id", "Login profile", "profiles"),
      f("specialization", "Specialization", "text", true),
      f("phone", "Phone"),
      f("skills", "Skills", "textarea"),
      notes,
    ],
    ["Available", "Assigned", "Travelling", "On Site", "Busy", "Off Duty", "Leave"],
    ["specialization", "phone", "jobs_today", "assigned_jobs", "completed_jobs"],
    { computed: ["jobs_today", "assigned_jobs", "completed_jobs"] },
  ),
  work_orders: entity(
    "Work orders",
    "Work order",
    "WO",
    "From dispatch to completion, every step is connected.",
    [
      customer,
      site,
      asset,
      r("complaint_id", "Service case", "complaints"),
      engineer,
      f("scheduled_at", "Scheduled time", "datetime-local", true),
      priority,
      f("problem", "Reported issue", "textarea"),
      f("diagnosis", "Diagnosis", "textarea"),
      f("work_performed", "Work performed", "textarea"),
      f("recommendations", "Recommendations", "textarea"),
      f("customer_confirmation", "Customer confirmation", "textarea"),
    ],
    [
      "Scheduled",
      "Assigned",
      "Travelling",
      "On Site",
      "In Progress",
      "Waiting Parts",
      "Completed",
      "Cancelled",
    ],
    ["customer_id", "equipment_id", "engineer_id", "scheduled_at", "priority"],
    { create: false, edit: false },
  ),
  work_order_readings: entity(
    "Readings",
    "Reading",
    "RDG",
    "Capture actual mechanical, electrical and controls readings.",
    [
      r("work_order_id", "Work order", "work_orders", true),
      num("value", "Measured value", -100000),
      f("unit", "Unit", "text", true),
      notes,
    ],
    ["Recorded"],
    ["value", "unit"],
  ),
  work_order_parts: entity(
    "Parts used",
    "Part",
    "PRT",
    "Parts consumed during this service visit.",
    [
      r("work_order_id", "Work order", "work_orders", true),
      num("quantity", "Quantity", 0.001),
      f("unit", "Unit", "text", true),
      notes,
    ],
    ["Used"],
    ["quantity", "unit"],
  ),
  work_order_activities: entity(
    "Job timeline",
    "Activity",
    "WAC",
    "A record of travel, arrival, work and completion.",
    [r("work_order_id", "Work order", "work_orders", true), notes],
    ["Recorded"],
    ["created_at"],
    { create: false, edit: false },
  ),
  amc_contracts: entity(
    "AMC contracts",
    "AMC contract",
    "AMC",
    "Plan coverage, visits and renewals before they become urgent.",
    [
      customer,
      site,
      f("start_date", "Start date", "date", true),
      f("end_date", "End date", "date", true),
      o("frequency", "Visit frequency", ["Monthly", "Quarterly", "Semiannual", "Annual"]),
      num("planned_visits", "Planned visits", 1),
      f("next_visit", "Next visit", "date"),
      f("renewal_date", "Renewal date", "date"),
      notes,
    ],
    ["Draft", "Active", "Expiring", "Expired"],
    ["customer_id", "end_date", "frequency", "next_visit"],
  ),
  amc_equipment: entity(
    "Asset coverage",
    "Coverage",
    "COV",
    "Assets explicitly covered by this contract.",
    [r("amc_id", "Contract", "amc_contracts", true), asset],
    ["Covered"],
    ["amc_id", "equipment_id"],
  ),
  pm_schedules: entity(
    "Preventive maintenance",
    "PM schedule",
    "PM",
    "Upcoming, due and overdue maintenance visits.",
    [
      customer,
      site,
      asset,
      r("amc_id", "AMC contract", "amc_contracts"),
      engineer,
      f("planned_date", "Planned date", "date", true),
      o("frequency", "Frequency", ["Monthly", "Quarterly", "Semiannual", "Annual"]),
      notes,
    ],
    ["Upcoming", "Due", "Overdue", "Assigned", "Completed"],
    ["customer_id", "equipment_id", "planned_date", "engineer_id"],
  ),
  pm_visits: entity(
    "Completed PM visits",
    "PM visit",
    "PMV",
    "Completed preventive maintenance and linked work orders.",
    [
      r("schedule_id", "Schedule", "pm_schedules", true),
      r("work_order_id", "Work order", "work_orders", true),
      f("visit_date", "Visit date", "date", true),
      notes,
    ],
    ["Completed"],
    ["schedule_id", "visit_date"],
    { create: false, edit: false },
  ),
  service_reports: entity(
    "Service reports",
    "Service report",
    "SR",
    "Professional service records, ready to share and print.",
    [
      customer,
      site,
      asset,
      r("work_order_id", "Work order", "work_orders", true),
      engineer,
      f("visit_date", "Visit date", "date"),
      f("reported_issue", "Reported issue", "textarea"),
      f("diagnosis", "Diagnosis", "textarea"),
      f("work_completed", "Work completed", "textarea"),
      f("recommendations", "Recommendations", "textarea"),
      f("customer_confirmation", "Customer confirmation", "textarea"),
    ],
    ["Completed"],
    ["customer_id", "equipment_id", "engineer_id", "visit_date"],
    { create: false, edit: false },
  ),
  documents: entity(
    "Documents",
    "Document",
    "DOC",
    "Private attachments linked to your operational records.",
    [
      customer,
      r("work_order_id", "Work order", "work_orders"),
      r("equipment_id", "Asset", "equipment"),
      r("site_id", "Site", "sites"),
      r("quotation_id", "Quotation", "quotations"),
      r("project_id", "Project", "projects"),
      r("complaint_id", "Complaint", "complaints"),
      r("amc_id", "AMC", "amc_contracts"),
      r("service_report_id", "Service report", "service_reports"),
    ],
    ["Available"],
    ["customer_id", "mime_type", "created_at"],
    { create: false, edit: false },
  ),
  notifications: entity(
    "Notifications",
    "Notification",
    "NTF",
    "Actions that need your attention.",
    [],
    ["Unread", "Read"],
    ["entity_type", "created_at"],
    { create: false, edit: false },
  ),
  activity_log: entity(
    "Activity",
    "Activity",
    "ACT",
    "Meaningful changes across the operation.",
    [],
    ["Recorded"],
    ["entity_type", "created_at"],
    { create: false, edit: false },
  ),
};
export const mainEntities = [
  "customers",
  "enquiries",
  "quotations",
  "projects",
  "equipment",
  "complaints",
  "engineers",
  "work_orders",
  "amc_contracts",
  "pm_schedules",
  "service_reports",
  "documents",
];
export function getEntity(key: string): Entity {
  if (!Object.hasOwn(catalog, key)) throw new Error("Unknown module.");
  return catalog[key];
}
export function fieldsFor(key: string): string {
  const e = getEntity(key);
  return [
    ...new Set([
      "id",
      "tenant_id",
      "code",
      "name",
      "status",
      "created_at",
      ...e.fields.map((f) => f.key),
      ...e.columns.filter((c) => !e.computed?.includes(c)),
      ...(key === "documents" ? ["storage_path", "mime_type", "size_bytes"] : []),
      ...(key === 'quotations' ? ['subtotal','discount_amount','taxable_amount','tax_amount','grand_total','currency'] : []),
      ...(key === 'quotation_items' ? ['line_subtotal','discount_amount','taxable_amount','tax_amount','line_total'] : []),
      ...(key === "notifications" || key === "activity_log"
        ? ["entity_type", "entity_id", "notes"]
        : []),
      ...(key === "complaints"
        ? ["classification", "engineer_id", "override_reason", "override_at"]
        : []),
      ...(key === "work_orders" ? ["completed_at"] : []),
    ]),
  ].join(",");
}
