import type {Entity,Field} from './catalog';
const text=(key:string,label:string,type:Field['type']='text',required=false):Field=>({key,label,type,required});
const ref=(key:string,label:string,entity:string,required=false):Field=>({key,label,ref:entity,required});
const money=(key:string,label:string,required=false):Field=>text(key,label,'money',required);
const choice=(key:string,label:string,options:string[],required=true):Field=>({key,label,options,required});
const customer=ref('customer_id','Customer','customers',true),project=ref('project_id','Project','projects'),work=ref('work_order_id','Work order','work_orders'),notes=text('notes','Notes','textarea');
const name=text('name','Description','text',true);
const lineFields=[text('quantity','Quantity','decimal',true),text('unit','Unit','text',true),money('unit_price','Unit price (OMR)',true),text('discount','Discount (%)','decimal',true),text('tax','Tax (%)','decimal',true)];
function entry(label:string,singular:string,fields:Field[],columns:string[],statuses:string[],editable=true):Entity{return {label,singular,prefix:singular.slice(0,3).toUpperCase(),description:'Commercial values, billing and collections connected to your operational records.',fields:[name,...fields],columns,statuses,create:editable,edit:editable};}
export const financeCatalog:Record<string,Entity>={
 invoices:entry('Invoices','Invoice',[customer,choice('source_type','Billing source',['General','Project','AMC','Service']),project,ref('amc_id','AMC contract','amc_contracts'),work,text('invoice_date','Invoice date','date',true),text('due_date','Due date','date',true),notes],['customer_id','source_type','due_date','total','paid_amount','balance'],['Draft','Issued','Partially Paid','Paid','Overdue','Cancelled']),
 invoice_items:entry('Invoice items','Invoice item',[ref('invoice_id','Invoice','invoices',true),...lineFields],['quantity','unit_price','discount','tax','line_total'],['Active']),
 payments:entry('Payments','Payment',[ref('invoice_id','Invoice','invoices',true),text('payment_date','Payment date','date',true),money('amount','Payment amount (OMR)',true),choice('method','Payment method',['Bank Transfer','Cheque','Cash','Card','Other']),text('transaction_reference','Transaction / cheque reference'),notes],['invoice_id','payment_date','amount','method','transaction_reference'],['Recorded','Reversed']),
 receivables:entry('Receivables','Receivable',[customer,project,ref('amc_id','AMC contract','amc_contracts'),text('invoice_date','Invoice date','date'),text('due_date','Due date','date')],['customer_id','due_date','total','paid_amount','balance','days_overdue'],['Issued','Partially Paid','Overdue'],false),
 project_financials:entry('Project financials','Project financial record',[customer,ref('project_id','Project','projects',true),money('base_value','Base project value (OMR)'),money('estimated_cost','Estimated cost (OMR)'),money('actual_cost_override','Actual cost override (OMR)'),money('recognized_revenue','Recognized revenue (OMR)'),notes],['project_id','base_value','estimated_cost','recognized_revenue'],['Recorded']),
 project_variations:entry('Project variations','Variation',[customer,ref('project_id','Project','projects',true),text('variation_date','Variation date','date',true),money('amount','Variation amount (OMR)',true),notes],['project_id','variation_date','amount','approved_at'],['Draft','Submitted','Approved','Rejected']),
 amc_financials:entry('AMC financials','Contract financial record',[customer,ref('amc_id','AMC contract','amc_contracts',true),money('contract_value','Contract value (OMR)'),choice('billing_frequency','Billing frequency',['Monthly','Quarterly','Semi-Annual','Annual','Custom']),money('renewal_value','Renewal value (OMR)'),notes],['amc_id','contract_value','billing_frequency','renewal_value'],['Recorded']),
 service_charges:entry('Service charges','Service charge',[customer,ref('work_order_id','Work order','work_orders',true),money('inspection_fee','Inspection fee (OMR)',true),money('labour_charge','Labour charge (OMR)',true),money('parts_charge','Additional parts charge (OMR)',true),money('other_charges','Other charges (OMR)',true),text('discount','Discount (%)','decimal',true),text('tax','Tax (%)','decimal',true),text('extra_charge_reason','Warranty / AMC extra charge authorization reason','textarea'),notes],['work_order_id','subtotal','tax_amount','total'],['Draft','Approved','Invoiced']),
 work_order_part_financials:entry('Part pricing','Part pricing',[customer,ref('part_id','Part used','work_order_parts',true),money('unit_cost','Unit cost (OMR)',true),money('unit_sell_price','Unit sell price (OMR)',true),choice('chargeable','Chargeable',['false','true']),notes],['part_id','unit_cost','unit_sell_price','chargeable'],['Recorded']),
 cost_records:entry('Operational costs','Cost record',[customer,project,work,choice('cost_type','Cost type',['Materials','Labour','Subcontractor','Transport','Equipment','Other']),text('cost_date','Cost date','date',true),text('supplier','Supplier'),text('quantity','Quantity','decimal',true),money('unit_cost','Unit cost (OMR)',true),notes],['project_id','work_order_id','cost_type','cost_date','total_cost'],['Recorded']),
};
financeCatalog.project_financial_summary=entry('Project financial summary','Project financial summary',[customer,project],['project_status','project_revenue','invoiced_amount','paid_amount','outstanding_amount','actual_cost','gross_profit','gross_margin_percent'],['Recorded'],false);
financeCatalog.amc_financial_summary=entry('AMC financial summary','AMC financial summary',[customer,ref('amc_id','AMC contract','amc_contracts')],['contract_value','billing_frequency','amount_billed','amount_paid','outstanding','end_date'],['Recorded'],false);
export const financeEntities=Object.keys(financeCatalog);
export const moneyKeys=new Set(['quotation_amount','grand_total','unit_price','base_value','quoted_value','variation_value','approved_variation_value','project_revenue','invoiced_amount','paid_amount','outstanding_amount','estimated_cost','actual_cost','actual_cost_override','recognized_revenue','gross_profit','contract_value','renewal_value','amount_billed','amount_paid','outstanding','amount','balance','subtotal','discount_amount','taxable_amount','tax_amount','total','line_subtotal','line_total','unit_cost','unit_sell_price','total_cost','inspection_fee','labour_charge','parts_charge','recorded_parts_charge','other_charges']);
